services:
    gotify:
        container_name: gotify
        image: gotify/server
        restart: unless-stopped
        environment:
            - TZ="America/Buenos_Aires"
        volumes:
            - /var/gotify/data:/app/data
        ports:
            - 8099:80
        networks:
            - proxy_network

networks:
    proxy_network:
        external: true
