services:
    traefik:
        container_name: traefik
        image: traefik:latest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
            - ./traefik.yml:/traefik.yml:ro
            - ./acme.json:/acme.json
            - ./config.yml:/config.yml:ro
            - ./logs:/var/log/traefik
        networks:
            traefik_network:

networks:
    traefik_network:
        external: true
