services:
    nextcloud:
        container_name: nextcloud
        image: nextcloud:latest
        restart: always
        ports:
            - 8080:80
        volumes:
          - /mnt/disk2/nextcloud_data:/var/www/html
        networks:
            - proxy_network
        env_file: .env

networks:
    proxy_network:
        external: true
