services:
  linkwarden:
    container_name: linkwarden
    env_file: .env
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    networks:
      - proxy_network

networks:
    proxy_network:
        external: true
