services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        ports:
            - '8099:8080'
        volumes:
            - ./config:/var/jenkins_home
        networks:
            - proxy_network
    ssh-agent:
        image: jenkins/ssh-agent

networks:
    proxy_network:
        external: true
