services:
    cache:
        container_name: redis
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        env_file: .env
        volumes:
            - cache:/data
        networks:
            - proxy_network

volumes:
    cache:
        driver: local

networks:
    proxy_network:
        external: true
